name: samba_server_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  samba_server:
    git:
      url: https://github.com/tejHackerDEV/samba_server
      ref: develop
  build: ^2.3.1
  source_gen: ^1.2.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
